branch-defaults:
  main:
    environment: breederhq-api-dev
environment-defaults:
  breederhq-api-dev:
    branch: null
    repository: null
global:
  application_name: breederhq-api-dev
  default_ec2_keyname: null
  default_platform: Node.js 24 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: bhq-dev
  sc: git
  workspace_type: Application
